[Interface]
# Adresse IP du serveur dans le tunnel VPN
Address = 10.8.0.1/24
ListenPort = 51820 
PrivateKey = clé privé du serveur

# Règles de pare-feu pour autoriser le routage du trafic VPN vers le LAN
PostUp = iptables -A FORWARD -i wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -o ens18 -j MASQUERADE
PostDown = iptables -D FORWARD -i wg0 -j ACCEPT; iptables -t nat -D POSTROUTING -o ens18 -j MASQUERADE

[Peer]
# Informations du client externe
PublicKey = clé publique du client
# L'IP que le client aura dans le tunnel
AllowedIPs = 10.8.0.2/32